version: "3.7"
services:

  web:
    command: uvicorn jeopardy.app:app --host=0.0.0.0 --reload
    build:
      context: .
      target: jeopardy_web
    depends_on:
      - database
    environment:
      DATABASE_URI: "mysql://web:web_password@database:3306/jeopardy"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "jeopardy"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "web_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - 3305:3306
