version: "3.7"
services:

  web:
    command: python -m sanic jeopardy.app.app --host=0.0.0.0 --port=8000 --workers=1
    build:
      context: .
      target: jeopardy_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "jeopardy"
      MYSQL_USER: "web"
      MYSQL_PASSWORD: "web_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - 3305:3306
